<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit98acb85f6c374a49816eb1628d9bb58a
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Curl\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Curl\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-curl-class/php-curl-class/src/Curl',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit98acb85f6c374a49816eb1628d9bb58a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit98acb85f6c374a49816eb1628d9bb58a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit98acb85f6c374a49816eb1628d9bb58a::$classMap;

        }, null, ClassLoader::class);
    }
}
