<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbf0f5873b523595b703de5076bd0ddd1
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'VStelmakh\\UrlHighlight\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'VStelmakh\\UrlHighlight\\' => 
        array (
            0 => __DIR__ . '/..' . '/vstelmakh/url-highlight/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbf0f5873b523595b703de5076bd0ddd1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbf0f5873b523595b703de5076bd0ddd1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbf0f5873b523595b703de5076bd0ddd1::$classMap;

        }, null, ClassLoader::class);
    }
}
